import type { GroceryItemData } from "@/components/groceryitem"

export const MOCK_GROCERY_LIST: GroceryItemData[] = [
  // Grains
  {
    fdc_id: 169704,
    description: "Brown Rice, Long Grain, Dry",
    food_category: "Grains & Bread",
    household_serving: "1/4 cup dry",
    calories: 171,
    protein_g: 4,
    carbs_g: 36,
    fat_g: 1,
    fiber_g: 2,
    sodium_mg: 3,
    price_usd: 1.89,
    score: 94,
    tags: ["vegan", "gluten-free", "low sodium"],
  },
  {
    fdc_id: 325871,
    description: "Old Fashioned Rolled Oats",
    brand_name: "Quaker",
    food_category: "Grains & Bread",
    household_serving: "1/2 cup dry",
    calories: 150,
    protein_g: 5,
    carbs_g: 27,
    fat_g: 3,
    fiber_g: 4,
    sodium_mg: 0,
    price_usd: 2.49,
    score: 91,
    tags: ["vegan", "low sodium"],
  },
  {
    fdc_id: 168882,
    description: "Whole Wheat Bread, 100%",
    brand_name: "Nature's Own",
    food_category: "Grains & Bread",
    household_serving: "1 slice (43g)",
    calories: 110,
    protein_g: 4,
    carbs_g: 20,
    fat_g: 2,
    fiber_g: 3,
    sodium_mg: 160,
    price_usd: 3.29,
    score: 83,
    tags: ["vegetarian"],
  },

  // Proteins
  {
    fdc_id: 173757,
    description: "Canned Chickpeas (Garbanzo Beans), Low Sodium",
    brand_name: "Bush's Best",
    food_category: "Beans & Legumes",
    household_serving: "1/2 cup (130g)",
    calories: 120,
    protein_g: 6,
    carbs_g: 22,
    fat_g: 1,
    fiber_g: 6,
    sodium_mg: 140,
    price_usd: 1.19,
    score: 97,
    tags: ["vegan", "gluten-free", "halal", "kosher"],
  },
  {
    fdc_id: 175167,
    description: "Black Beans, Canned, No Salt Added",
    brand_name: "Great Value",
    food_category: "Beans & Legumes",
    household_serving: "1/2 cup (130g)",
    calories: 110,
    protein_g: 7,
    carbs_g: 20,
    fat_g: 0,
    fiber_g: 8,
    sodium_mg: 15,
    price_usd: 0.98,
    score: 96,
    tags: ["vegan", "gluten-free", "low sodium"],
  },
  {
    fdc_id: 171477,
    description: "Chicken Breast, Boneless Skinless, Raw",
    food_category: "Meat & Poultry",
    household_serving: "4 oz (113g)",
    calories: 130,
    protein_g: 26,
    carbs_g: 0,
    fat_g: 3,
    fiber_g: 0,
    sodium_mg: 74,
    price_usd: 3.99,
    score: 89,
    tags: ["gluten-free", "low sodium", "halal"],
  },
  {
    fdc_id: 175168,
    description: "Large Eggs, Grade A",
    brand_name: "Eggland's Best",
    food_category: "Dairy & Eggs",
    household_serving: "1 egg (50g)",
    calories: 70,
    protein_g: 6,
    carbs_g: 0,
    fat_g: 5,
    fiber_g: 0,
    sodium_mg: 65,
    price_usd: 3.49,
    score: 88,
    tags: ["vegetarian", "gluten-free"],
  },
  {
    fdc_id: 174290,
    description: "Canned Tuna in Water, Light",
    brand_name: "StarKist",
    food_category: "Seafood",
    household_serving: "1 pouch (74g)",
    calories: 80,
    protein_g: 17,
    carbs_g: 0,
    fat_g: 1,
    fiber_g: 0,
    sodium_mg: 270,
    price_usd: 1.29,
    score: 85,
    tags: ["gluten-free", "dairy-free"],
  },

  // Dairy
  {
    fdc_id: 746776,
    description: "Greek Yogurt, Plain, Nonfat",
    brand_name: "Chobani",
    food_category: "Dairy & Eggs",
    household_serving: "3/4 cup (170g)",
    calories: 90,
    protein_g: 15,
    carbs_g: 6,
    fat_g: 0,
    fiber_g: 0,
    sodium_mg: 65,
    price_usd: 1.49,
    score: 92,
    tags: ["vegetarian", "gluten-free"],
  },
  {
    fdc_id: 172186,
    description: "Skim Milk, Nonfat",
    food_category: "Dairy & Eggs",
    household_serving: "1 cup (240ml)",
    calories: 83,
    protein_g: 8,
    carbs_g: 12,
    fat_g: 0,
    fiber_g: 0,
    sodium_mg: 103,
    price_usd: 1.09,
    score: 87,
    tags: ["vegetarian", "gluten-free"],
  },

  // Produce
  {
    fdc_id: 170379,
    description: "Spinach, Fresh Baby",
    brand_name: "Dole",
    food_category: "Vegetables",
    household_serving: "2 cups (56g)",
    calories: 13,
    protein_g: 2,
    carbs_g: 2,
    fat_g: 0,
    fiber_g: 1,
    sodium_mg: 47,
    price_usd: 2.99,
    score: 98,
    tags: ["vegan", "gluten-free", "low sodium"],
  },
  {
    fdc_id: 170438,
    description: "Sweet Potatoes, Raw",
    food_category: "Vegetables",
    household_serving: "1 medium (130g)",
    calories: 112,
    protein_g: 2,
    carbs_g: 26,
    fat_g: 0,
    fiber_g: 4,
    sodium_mg: 72,
    price_usd: 0.79,
    score: 95,
    tags: ["vegan", "gluten-free", "low sodium"],
  },
  {
    fdc_id: 173945,
    description: "Bananas, Raw",
    food_category: "Fruit",
    household_serving: "1 medium (118g)",
    calories: 105,
    protein_g: 1,
    carbs_g: 27,
    fat_g: 0,
    fiber_g: 3,
    sodium_mg: 1,
    price_usd: 0.29,
    score: 93,
    tags: ["vegan", "gluten-free", "low sodium"],
  },
  {
    fdc_id: 168409,
    description: "Apples, Fuji, Raw",
    food_category: "Fruit",
    household_serving: "1 medium (182g)",
    calories: 95,
    protein_g: 0,
    carbs_g: 25,
    fat_g: 0,
    fiber_g: 4,
    sodium_mg: 2,
    price_usd: 0.89,
    score: 90,
    tags: ["vegan", "gluten-free", "low sodium"],
  },
  {
    fdc_id: 170000,
    description: "Frozen Broccoli Florets",
    brand_name: "Birds Eye",
    food_category: "Vegetables",
    household_serving: "1 cup (85g)",
    calories: 30,
    protein_g: 3,
    carbs_g: 6,
    fat_g: 0,
    fiber_g: 3,
    sodium_mg: 25,
    price_usd: 1.99,
    score: 96,
    tags: ["vegan", "gluten-free", "low sodium"],
  },

  // Fats & Oils
  {
    fdc_id: 171413,
    description: "Peanut Butter, Natural, No Added Sugar",
    brand_name: "Smucker's",
    food_category: "Fats & Oils",
    household_serving: "2 tbsp (32g)",
    calories: 190,
    protein_g: 8,
    carbs_g: 7,
    fat_g: 16,
    fiber_g: 2,
    sodium_mg: 105,
    price_usd: 3.49,
    score: 82,
    tags: ["vegan", "gluten-free"],
  },
  {
    fdc_id: 789034,
    description: "Extra Virgin Olive Oil",
    brand_name: "Kirkland Signature",
    food_category: "Fats & Oils",
    household_serving: "1 tbsp (14g)",
    calories: 120,
    protein_g: 0,
    carbs_g: 0,
    fat_g: 14,
    fiber_g: 0,
    sodium_mg: 0,
    price_usd: 7.99,
    score: 79,
    tags: ["vegan", "gluten-free", "low sodium"],
  },
]

export const MOCK_RESPONSE = {
  items: MOCK_GROCERY_LIST,
  estimated_weekly_cost: 43.59,
}
